---
- name: Create upgrade stage directory
  file:
    path: "{{ oracle_stage }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    state: directory
  tags: always

- name: Run pre-checks
  include: pre_checks.yml
  when: master_node
  tags:
    - always
    - pre_checks

- name: get DB Unique Name
  include: get_unique_name.yml
  when: master_node
  tags:
    - always
    - unique_name

#Run pre-upgrade tasks one day before upgrade
- name: run pre-upgrade tasks
  include: pre_upgrade.yml
  when: pre_upgrade and master_node
  tags: pre_upgrade

#Upgrade database to 12.1.0.2
- name: upgrade database
  include: upgrade_{{ oracle_install_type }}.yml
  when: upgrade
  tags: upgrade

#Upgrade Timezone
- name: upgrade timezone
  include: upgrade_tzv.yml
  when: upgrade_tzv
  tags: upgrade_tzv

#Run final upgrade tasks 1 week after upgrading database
- name: final upgrade tasks
  include: upgrade_final.yml
  when: upgrade_final
  tags: upgrade_final
