---
- name: Template enable_archivelog (noarchivelog)
  template:
    src: enable_archivelog.j2
    dest: "{{ oracle_stage }}/enable_archivelog.sql"
  when: database_parameters[db_name].log_mode == 'noarchivelog'
  tags: archivelog

- name: Shutdown database (single instance noarchivelog)
  shell: echo "shutdown immediate;" | sqlplus / as sysdba
  environment: "{{ env_old }}"
  when: database_parameters[db_name].log_mode == 'noarchivelog' and oracle_install_type == 'si'
  tags:
    - archivelog

- name: Shutdown database (rac, noarchivelog)
  shell: srvctl stop database -d {{ db_name }}
  environment: "{{ env_old }}"
  when: database_parameters[db_name].log_mode == 'noarchivelog' and oracle_install_type == 'rac'
  tags:
    - archivelog

- name: Startup Mount (noarchivelog)
  shell: echo "startup mount;" | sqlplus / as sysdba
  environment: "{{ env_old }}"
  when: database_parameters[db_name].log_mode == 'noarchivelog'
  tags:
    - archivelog

- name: Run enable_archivelog.sql
  shell: echo exit | sqlplus / as sysdba @enable_archivelog.sql
  args:
    chdir: "{{ oracle_stage }}"
  environment: "{{ env_old }}"
  when: database_parameters[db_name].log_mode == 'noarchivelog'
  tags: archivelog

- name: Startup database (rac, noarchivelog)
  shell: srvctl start database -d {{ db_name }}
  environment: "{{ env_old }}"
  when: database_parameters[db_name].log_mode == 'noarchivelog' and oracle_install_type == 'rac'
  tags:
    - archivelog

# Backup Database
- name: template backup script (level 0)
  template:
    src: pre_upgrade_backup_0.j2
    dest: "{{ oracle_stage }}/pre_upgrade_backup_0.rman"
  tags: pre_upgrade_backup

- name: backup database (level 0)
  shell: rman @{{ oracle_stage }}/pre_upgrade_backup_0.rman
  environment: "{{ env_old }}"
  async: 7200
  poll: 10
  tags: pre_upgrade_backup

- name: Run preupgrade utility
  shell: "{{ oracle_base }}/{{ oracle_version }}/dbhome_1/jdk/bin/java -jar preupgrade.jar TERMINAL TEXT"
  args:
    chdir: "{{ oracle_base }}/{{ oracle_version }}/dbhome_1/rdbms/admin"
  environment: "{{ env_old }}"
  register: preupgrade_output
  tags: preupgrade

- name: Print preupgrade utility output before continuing
  debug: var=preupgrade_output.stdout_lines
  tags: preupgrade

- pause:
    prompt: Check preupgrade utility output to confirm no issues

- name: Run preupgrade_fixups.sql
  shell: echo exit | sqlplus / as sysdba @preupgrade_fixups.sql
  args:
    chdir: "{{ oracle_base }}/cfgtoollogs/{{ db_unique_name }}/preupgrade/"
  register: fixups
  environment: "{{ env_old }}"

- debug: var=fixups.stdout_lines

- name: Copy fixups output to oracle_stage
  copy: content="{{ fixups.stdout }}" dest="{{ oracle_stage }}/preupgrade_fixups.log"

- pause:
    prompt: Check preupgrade_fixups output before continuing

- name: Template pre_upgrade_tasks.sql
  template:
    src: pre_upgrade_tasks.j2
    dest: "{{ oracle_stage }}/pre_upgrade_tasks.sql"

- name: Run pre_upgrade_tasks.sql
  shell: echo exit | sqlplus / as sysdba @pre_upgrade_tasks.sql
  args:
    chdir: "{{ oracle_stage }}"
  environment: "{{ env_old }}"
  register: pre_upgrade_tasks_output

- debug: var=pre_upgrade_tasks_output.stdout_lines

- pause:
    prompt: Review output of pre_upgrade_tasks script before continuing
