---
# Steps to upgrade Timezone on 12c Database
# See MOS Note: Scripts to automatically update the RDBMS DST (timezone) version in an 11gR2 or 12cR1 database . (Doc ID 1585343.1)

- name: copy scripts to oracle_stage
  copy:
    src: "{{ item }}"
    dest: "{{ oracle_stage }}"
  with_items:
    - upg_tzv_apply.sql
    - upg_tzv_check.sql

- name: run upg_tzv_check.sql
  shell: echo exit | sqlplus / as sysdba @upg_tzv_check.sql
  args:
    chdir: "{{ oracle_stage }}"
  register: tzv_check
  environment: "{{ env }}"

- debug: var=tzv_check

- name: run upg_tzv_apply.sql (
  shell: echo exit | sqlplus / as sysdba @upg_tzv_apply.sql
  args:
    chdir: "{{ oracle_stage }}"
  register: tzv_apply
  environment: "{{ env }}"

- debug: var=tzv_apply
