---
#Steps to run 1 Week after upgrading Database

- name: Final | Template upgrade_final_tasks.sql (restarts database)
  template:
    src: upgrade_final_tasks.j2
    dest: "{{ oracle_stage }}/upgrade_final_tasks.sql"

- name: Final | Run upgrade_final_tasks.sql
  shell: echo exit | sqlplus / as sysdba @upgrade_final_tasks.sql
  args:
    chdir: "{{ oracle_stage }}"
  environment: env

## Backup Database
- name: template final upgrade backup (level 0)
  template:
    src: final_upgrade_backup_0.j2
    dest: "{{ oracle_stage }}/final_upgrade_backup_0.rman"
  when: database_parameters[db_name].log_mode == 'archivelog'
  tags: final_upgrade_backup

- name: final upgrade backup (level 0)
  shell: rman @{{ oracle_stage }}/final_upgrade_backup_0.rman
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
    PATH: "{{ oracle_home }}/bin"
    NLS_DATE_FORMAT: 'Mon DD YYYY HH24:MI:SS'
  async: 7200
  poll: 10
  when: database_parameters[db_name].log_mode == 'archivelog'
  tags: final_upgrade_backup
  register: final_upg
  failed_when: "final_upg.rc != 1" # 12.1 rman sends rc = 1 after successful backup!?
